spring:
  config:
    activate:
      on-profile: "prod"

  jpa:
    hibernate:
      ddl-auto: none

api:
  base-url: ${API_BASE_URL}

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG