spring:
  config:
    activate:
      on-profile: "storage"

cloud:
  aws:
    region:
      auto: false
      static: ${AWS_REGION:}
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET:}
      endpoint: ${S3_ENDPOINT:https://s3.ap-northeast-2.amazonaws.com}
    credentials:
      access-key: ${AWS_ACCESS_KEY:}
      secret-key: ${AWS_SECRET_KEY:}