spring:
  config:
    activate:
      on-profile: "dev"

  jpa:
    hibernate:
      ddl-auto: update

api:
  base-url: ENC(RXhO8E8bq24tU28ImTaecQ==)

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG